### ISSUE TITLE
Must define root query type

### ISSUE THREAD

**Issue by MARTIMM** [CurtTilmes/Perl6-GraphQL#3]
Hi Curt,

The error `Must define root query type` is returned when a class is given to a `GraphQL::Schema` object, where the class name is not specifically called `Query`. Is there a reason that the name is fixed?

Regards,
Marcel

**Comment by CurtTilmes** [comment]
You can change it with the :query parameter to Schema.new().  It just defaults to Query if you don't otherwise specify it.

**Comment by MARTIMM** [comment]
Thank you Curt, it works
